class Office < ApplicationRecord
  validates :name, :category, :division, :district, :address, presence: true

  enum category: {
    head: 0,
    zonal: 1,
    sub_zonal: 2
  }
  enum division: {
    dhaka: 0,
    khulna: 1,
    rajshahi: 2,
    rangpur: 3,
    mymenshingh: 4,
    chattogram: 5,
    sylhet: 6,
    barisal: 7
  }
  enum district: {
    Khulna: 0,
    Dhaka: 1,
    Barishal: 2,
    Chattogram: 3,
    Rajshahi: 4,
    Rangpur: 5,
    Sylhet: 6,
    Mymensingh: 7,
    Bagerhat: 8,
    Bandarban: 9,
    Barguna: 10,
    Bhola: 11,
    Bogura: 12,
    Brahmanbaria: 13,
    Chandpur: 14,
    Chapainawabganj: 15,
    Chuadanga: 16,
    CoxsBazar: 17,
    Cumilla: 18,
    Dinajpur: 19,
    Faridpur: 20,
    Feni: 21,
    Gaibandha: 22,
    Gazipur: 23,
    Gopalganj: 24,
    Habiganj: 25,
    Jamalpur: 26,
    Jashore: 27,
    Jhalokati: 28,
    Jhenaidah: 29,
    Joypurhat: 30,
    Kishoreganj: 31,
    Kurigram: 32,
    Kushtia: 33,
    Lakshmipur: 34,
    Lalmonirhat: 35,
    Madaripur: 36,
    Magura: 37,
    Manikganj: 38,
    Meherpur: 39,
    Moulvibazar: 40,
    Munshiganj: 41,
    Naogaon: 42,
    Narail: 43,
    Narayanganj: 44,
    Narsingdi: 45,
    Natore: 46,
    Netrokona: 47,
    Nilphamari: 48,
    Noakhali: 49,
    Pabna: 50,
    Panchagarh: 51,
    Patuakhali: 52,
    Pirojpur: 53,
    Rajbari: 54,
    Rangamati: 55,
    Satkhira: 56,
    Shariatpur: 57,
    Sherpur: 58,
    Sirajganj: 59,
    Sunamganj: 60,
    Tangail: 61,
    Thakurgaon: 62
  }

end
